-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "demo" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "demo_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"demoo" text
);
--> statement-breakpoint
ALTER TABLE "demo" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "haha" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "haha_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"Name" text DEFAULT 'alice',
	"age" bigint
);
--> statement-breakpoint
ALTER TABLE "haha" ENABLE ROW LEVEL SECURITY;
*/